customCommands:
  - key: "b"
    command: "mkpr"
    context: "global"
    loadingText: "Creating pull request on BitBucket"

gui:
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

os:
  editPreset: 'nvim'
