customCommands:
  - key: "b"
    command: "mkpr"
    context: "global"
    loadingText: "Creating pull request on BitBucket"

gui:
  nerdFontsVersion: "3"
  spinner:
    frames:
      - '⠁'
      - '⠁'
      - '⠉'
      - '⠙'
      - '⠚'
      - '⠒'
      - '⠂'
      - '⠂'
      - '⠒'
      - '⠲'
      - '⠴'
      - '⠤'
      - '⠄'
      - '⠄'
      - '⠤'
      - '⠠'
      - '⠠'
      - '⠤'
      - '⠦'
      - '⠖'
      - '⠒'
      - '⠐'
      - '⠐'
      - '⠒'
      - '⠓'
      - '⠋'
      - '⠉'
      - '⠈'
      - '⠈'
    rate: 80

git:
  paging:
    colorArg: always
    pager: delta --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

os:
  editPreset: 'nvim'
